config/routes.rb
MusicApp::Application.routes.draw do
  resources :users, :only => [:index, :create, :show, :new]
  resource :session, :except => [:edit]
  resources :bands
end

app/models/album.rb
class Album < ActiveRecord::Base
	attr_accessible :band_id, :name, :recording_type
	validates :band_id, :name, :recording_type, :presence => true

	belongs_to(:band,
						 :class_name => 'Band',
						 :primary_key => 'id',
						 :foreign_key => 'band_id')

	has_many(:tracks,
		:class_name => 'Track',
		:primary_key => 'id',
		:foreign_key => 'album_id',
		:dependent => :destroy)
end

app/models/band.rb
class Band < ActiveRecord::Base
	attr_accessible :name
	validates :name, :presence => true, :uniqueness => :true

	has_many(:albums,
		:class_name => 'Album',
		:primary_key => 'id',
		:foreign_key => 'band_id')

	has_many(:tracks, :through => :albums, :source => :tracks)

	def self.find_by_name(name)
		Band.where(:name => name).first
	end
end

app/models/track.rb
class Track < ActiveRecord::Base
	attr_accessible :number, :album_id, :name, :bonus, :lyrics
	validates :number, :album_id, :name, :bonus, :presence => true

	belongs_to(:album,
		:class_name => 'Album',
		:primary_key => 'id',
		:foreign_key => 'album_id')

	has_one(:band, :through => :album, :source => :band)
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password, :session_token
	before_validation :reset_session_token, :on => :create
	validates :password, :length => {:minimum => 6}, :on => :create
	validates :email, :password_digest, :session_token, :presence => true
	validates :email, :session_token, :uniqueness => true


	def password=(password)
		@password = password
		password_digest = BCrypt::Password.create(password)
		self.password_digest = password_digest 
	end

	def password
		@password
	end

	def is_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end

	def self.generate_session_token
		SecureRandom::urlsafe_base64
	end

	def reset_session_token
		session_token = User.generate_session_token
		self.session_token = session_token
	end

	def reset_session_token!
		reset_session_token
		self.save!
	end

	def self.find_by_credentials(email, password)
		user = User.where(:email => email).first
		return user if user && user.is_password?(password)
		nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

	def index
		@bands = Band.order(:name)

		render :index
	end

	def show
		@band = Band.find(params[:id])

		render :show
	end

	def new
		render :new
	end

	def create
		@band = Band.new(params[:band])

		if @band.save
			flash[:messages] = ["This is a newly added band!"]
			redirect_to(band_url(@band))
		else
			flash.now[:errors] = @band.errors.full_messages
			render :new
		end
	end

	def destroy
		@band = Band.find(params[:id])
		Band.delete(params[:id])
		flash[:messages] = ["You just deleted #{@band.name}."]
		redirect_to(bands_url)
	end

	def edit
		@band = Band.find(params[:id])
		
		render :edit

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include SessionsHelper
	include UsersHelper

	def new
		render :new
	end

	def create
		@user = User.find_by_credentials(params[:user][:email], 
																		params[:user][:password])
		if @user
			login!(@user)
			flash[:messages] = ["WE MISSED YOU SO MUCH. @_@"]

			redirect_to(user_url(@user))
		else
			flash.now[:errors] = ["Invalid email/password combination."]
			render :new
		end
	end

	def destroy
		user = current_user
		user.reset_session_token!
		session[:session_token] = nil

		redirect_to(new_session_url)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include UsersHelper

	def index
		@users = User.all

		render :index
	end

	def show
		@user = User.where(:id => params[:id]).first
	end

	def create
		@user = User.new(params[:user])
		if @user.save!
			flash[:message] = ["Signup Successful!"]
			login!
			redirect_to(user_url(@user))
		else
			flash[:errors] = @user.errors.full_messages
			render :new
		end
	end

	def new
		render :new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		User.where(:session_token => session[:session_token]).first
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def login!(user)
		user.reset_session_token!
		session[:session_token] = user.session_token
	end
end

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name%></h1>
<form action = "<%= bands_url%>" method = "POST">
	<input type = "hidden" name = "_method" value = "PUT">
<label for = "band_name">Name:</label>
<input type = "text" id = "band_name" name = "<%=@band.name%>">

app/views/bands/index.html.erb
<%unless flash[:messages].nil? %>
<ul>
	<% flash[:messages].each do |message| %>
	<li><%= message%></li>
	<%end%>
</ul>
<%end%>
<h1>Band Listing</h1>
<ul>
<% @bands.each do |band| %>
	<li><%= link_to("#{band.name}", band_url(band))%></li>
	<%end%>
</ul>

<%=link_to("Add a Band", new_band_url)%>

app/views/bands/new.html.erb
<% unless flash[:errors].nil? %>
<ul>
<% flash[:errors].each do |error_msg| %>
<li><%= "#{error_msg}"%></li>
<%end%>
</ul>
<%end%>
<h1>Add a Band</h1>
<form action = "<%=bands_url%>" method = "POST">
<label for = "band_name">Band Name:</label>
<input type "text" id = "band_name" name = "band[name]">

<input type = "Submit" value = "Add your Band">
</form>

app/views/bands/show.html.erb
<h1><%= "#{@band.name}"%></h1>
Welcome to our fanpage!

<%= button_to("Delete us!", band_url, :method => :delete)%>
<br>
<%= link_to("Back to the Bands Listing", bands_url)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%if logged_in?%>
<%= button_to("Logout", session_url, 
			:method => "delete")%>
<%end%>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Current Users</h1>
<ul>
	<% @users.each do |user| %>
	<li><%=link_to("#{user.email}", user_url(user))%>
	</li>
	<%end%>
</ul>
<%=link_to("Create a new account", new_user_url)%>

app/views/users/new.html.erb
<h1>CREATE AN ACCOUNT</h1>
<form action = "<%=users_url%>" method = "POST">
	<label for= "user_email">Email:</label>
	<input type = "text" id = "user_email" name = "user[email]">
	<label for= "user_password">Password:</label>
	<input type = "password" id = "user_password" name = "user[password]">

	<input type = "submit" value = "Create user">
</form>

app/views/users/show.html.erb
<h1><%="#{@user.email}"%></h1>
OMG FILLER FILLER FILLER